name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #A strategy creates a build matrix for your jobs. You can define different variations to run each job in.
    strategy:
     #matrix to create jobs for more than one supported version of a programming language, operating system
     matrix:
      node-version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      # set up the operating system
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      # run a single command: insall
      - name: Install dependencies
        run: npm install

      # the detailed operaion of test, build and lint can be found in package.json
        # run a single command:test
      - name: Run the tests
        run: npm test
        # run a single command:build
      - name: Build
        run: npm run build
         # run a single command: lint
      - name: Test lint
        run: npm run lint
